# Describes the format for available OpenRGB services

pull_devices:
  name: Pull devices
  description: Pull device list from OpenRGB server.

force_update:
  name: Force update
  description: Force all OpenRGB devices to pull data.

load_profile:
  name: Load profile
  description: Load profile in OpenRGB server
  fields:
    profile:
      name: Profile
      description: The name of the profile to load in the OpenRGB server
      required: true
      selector:
        text:
